enum NotificationType {
  deleteBoard,
  editBoardName,
  editTaskName,
  editTaskDescription,
  editTaskCompleted,
  editTaskDeadline,
  addTaskMember,
  addTaskComment,
  deleteTaskMember,
  deleteTask,
  editProjectName,
  editProjectDescription,
  addProjectMember,
  leaveProject,
  deleteProject,
  editProjectRole,
}
